"""services/delivery_service.py — per-type deliverers, idempotent replay,
and top-level dispatch() routing.

Complements the reserve()->consume() round-trip coverage already in
tests/test_inventory_and_idempotency.py with the non-key-backed deliverers
(DOWNLOADABLE_FILE, AUTO_GENERATED, MANUAL_DELIVERY, SERVICE) and the
dispatch() routing/legacy-fallback behaviour.
"""
import os
import unittest


def _setup_inmemory():
    os.environ.setdefault("BOT_TOKEN", "test:test")
    os.environ.setdefault("ADMIN_TELEGRAM_ID", "1")
    os.environ["DATABASE_URL"] = "sqlite:///:memory:"


class _BaseCase(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        _setup_inmemory()
        import importlib
        from database import db as db_mod
        importlib.reload(db_mod)
        from database.models import Base
        Base.metadata.create_all(db_mod.engine)

        import services.delivery_service as ds_mod
        importlib.reload(ds_mod)
        cls.ds = ds_mod

    def setUp(self):
        from database import get_db_session, User
        with get_db_session() as s:
            user = User(telegram_id=9000 + id(self) % 100000, username="buyer",
                       wallet_balance=0.0)
            s.add(user)
            s.commit()
            self.user_id = user.id

    def _make_product(self, product_type, **kwargs):
        from database import get_db_session, Product
        with get_db_session() as s:
            p = Product(name=f"P-{product_type.value}", price=9.99,
                       stock_count=0, product_type=product_type, is_active=True,
                       **kwargs)
            s.add(p)
            s.commit()
            return p.id

    def _make_order_with_item(self, product_id, quantity=1, total=9.99):
        from database import get_db_session, Order, OrderStatus, OrderItem
        with get_db_session() as s:
            o = Order(user_id=self.user_id, total_amount=total, status=OrderStatus.PROCESSING)
            s.add(o)
            s.flush()
            item = OrderItem(order_id=o.id, product_id=product_id, quantity=quantity, price=9.99)
            s.add(item)
            s.commit()
            return o.id, item.id


class DownloadableFileDeliveryTest(_BaseCase):
    def test_delivers_telegram_file_id(self):
        from database import ProductType
        product_id = self._make_product(ProductType.DOWNLOADABLE_FILE,
                                        telegram_file_id="FILEID123",
                                        telegram_file_type="document")
        order_id, _item_id = self._make_order_with_item(product_id)
        result = self.ds.dispatch(order_id)
        self.assertTrue(result.handled)
        self.assertTrue(result.success)
        self.assertEqual(result.assets, ["FILEID123"])
        self.assertIn("document attached above", result.user_message)

    def test_missing_file_and_link_returns_error(self):
        from database import ProductType
        product_id = self._make_product(ProductType.DOWNLOADABLE_FILE)
        order_id, _item_id = self._make_order_with_item(product_id)
        result = self.ds.dispatch(order_id)
        self.assertTrue(result.handled)
        self.assertFalse(result.success)
        self.assertIn("no telegram_file_id", result.error)

    def test_non_reusable_file_is_idempotent_on_replay(self):
        from database import ProductType
        product_id = self._make_product(ProductType.DOWNLOADABLE_FILE,
                                        download_link="https://example.com/file.zip",
                                        reusable=False)
        order_id, _item_id = self._make_order_with_item(product_id)
        first = self.ds.dispatch(order_id)
        self.assertTrue(first.success)
        self.assertFalse(first.idempotent_replay)

        second = self.ds.dispatch(order_id)
        self.assertTrue(second.success)
        self.assertTrue(second.idempotent_replay)


class AutoGeneratedDeliveryTest(_BaseCase):
    def test_generates_requested_quantity_of_values(self):
        from database import ProductType
        product_id = self._make_product(ProductType.AUTO_GENERATED,
                                        type_config='{"mode": "code", "length": 10}')
        order_id, _item_id = self._make_order_with_item(product_id, quantity=3)
        result = self.ds.dispatch(order_id)
        self.assertTrue(result.handled)
        self.assertTrue(result.success)
        self.assertEqual(len(result.assets), 3)
        self.assertEqual(len(set(result.assets)), 3, "generated values must be unique")

    def test_replay_returns_same_values_without_regenerating(self):
        from database import ProductType
        product_id = self._make_product(ProductType.AUTO_GENERATED,
                                        type_config='{"mode": "code", "length": 10}')
        order_id, _item_id = self._make_order_with_item(product_id, quantity=2)
        first = self.ds.dispatch(order_id)
        second = self.ds.dispatch(order_id)
        self.assertTrue(second.idempotent_replay)
        self.assertEqual(sorted(first.assets), sorted(second.assets))

    def test_prefix_and_suffix_applied(self):
        from database import ProductType
        product_id = self._make_product(
            ProductType.AUTO_GENERATED,
            type_config='{"mode": "code", "length": 8, "prefix": "GC-", "suffix": "-X"}',
        )
        order_id, _item_id = self._make_order_with_item(product_id, quantity=1)
        result = self.ds.dispatch(order_id)
        self.assertTrue(result.success)
        value = result.assets[0]
        self.assertTrue(value.startswith("GC-"))
        self.assertTrue(value.endswith("-X"))


class ManualDeliveryTest(_BaseCase):
    def test_creates_queued_task_once(self):
        from database import ProductType
        product_id = self._make_product(ProductType.MANUAL_DELIVERY)
        order_id, _item_id = self._make_order_with_item(product_id, quantity=2)

        first = self.ds.dispatch(order_id)
        self.assertTrue(first.handled)
        self.assertTrue(first.queued)
        self.assertFalse(first.idempotent_replay)
        self.assertIn("queued for manual delivery", first.user_message)

        second = self.ds.dispatch(order_id)
        self.assertTrue(second.queued)
        self.assertTrue(second.idempotent_replay)

        from database import get_db_session
        from database.models import ManualDeliveryTask
        with get_db_session() as s:
            tasks = s.query(ManualDeliveryTask).filter_by(order_id=order_id).all()
        self.assertEqual(len(tasks), 1, "repeat dispatch must not create a second task")


class ServiceDeliveryTest(_BaseCase):
    def test_creates_service_order_once(self):
        from database import ProductType
        product_id = self._make_product(ProductType.SERVICE)
        order_id, _item_id = self._make_order_with_item(product_id)

        first = self.ds.dispatch(order_id)
        self.assertTrue(first.queued)
        self.assertFalse(first.idempotent_replay)

        second = self.ds.dispatch(order_id)
        self.assertTrue(second.idempotent_replay)

        from database import get_db_session
        from database.models import ServiceOrder
        with get_db_session() as s:
            orders = s.query(ServiceOrder).filter_by(order_id=order_id).all()
        self.assertEqual(len(orders), 1)


class DispatchRoutingTest(_BaseCase):
    def test_legacy_key_type_returns_handled_false(self):
        """KEY/FILE are deliberately absent from the dispatch table so the
        legacy handlers/payment_handlers.py code path keeps handling them."""
        from database import ProductType
        product_id = self._make_product(ProductType.KEY)
        order_id, _item_id = self._make_order_with_item(product_id)
        result = self.ds.dispatch(order_id)
        self.assertFalse(result.handled)

    def test_legacy_file_type_returns_handled_false(self):
        from database import ProductType
        product_id = self._make_product(ProductType.FILE)
        order_id, _item_id = self._make_order_with_item(product_id)
        result = self.ds.dispatch(order_id)
        self.assertFalse(result.handled)

    def test_missing_order_returns_error(self):
        result = self.ds.dispatch(999_999)
        self.assertEqual(result.error, "Order not found")

    def test_order_with_no_items_returns_error(self):
        from database import get_db_session, Order, OrderStatus
        with get_db_session() as s:
            o = Order(user_id=self.user_id, total_amount=1.0, status=OrderStatus.PROCESSING)
            s.add(o)
            s.commit()
            order_id = o.id
        result = self.ds.dispatch(order_id)
        self.assertEqual(result.error, "Order has no items")

    def test_explicit_order_item_id_targets_correct_item_in_multi_item_order(self):
        """Regression coverage for the documented multi-item cart-checkout
        requirement: passing order_item_id must deliver THAT item, not
        always fall back to items[0]."""
        from database import ProductType, get_db_session, OrderItem, Order, OrderStatus

        product_a = self._make_product(ProductType.AUTO_GENERATED,
                                       type_config='{"mode": "code", "length": 8}')
        product_b = self._make_product(ProductType.MANUAL_DELIVERY)

        with get_db_session() as s:
            o = Order(user_id=self.user_id, total_amount=20.0, status=OrderStatus.PROCESSING)
            s.add(o)
            s.flush()
            item_a = OrderItem(order_id=o.id, product_id=product_a, quantity=1, price=10.0)
            item_b = OrderItem(order_id=o.id, product_id=product_b, quantity=1, price=10.0)
            s.add_all([item_a, item_b])
            s.commit()
            order_id, item_a_id, item_b_id = o.id, item_a.id, item_b.id

        result_b = self.ds.dispatch(order_id, order_item_id=item_b_id)
        self.assertTrue(result_b.queued)  # MANUAL_DELIVERY path, not AUTO_GENERATED

        with get_db_session() as s:
            item_a_row = s.query(OrderItem).filter_by(id=item_a_id).first()
        self.assertIsNone(item_a_row.delivered_asset, "untouched item must stay undelivered")

        from database.models import ManualDeliveryTask, GeneratedValue
        with get_db_session() as s:
            manual_tasks = s.query(ManualDeliveryTask).filter_by(order_id=order_id).all()
            generated = s.query(GeneratedValue).filter_by(order_id=order_id).all()
        self.assertEqual(len(manual_tasks), 1)
        self.assertEqual(manual_tasks[0].product_id, product_b)
        self.assertEqual(len(generated), 0, "the AUTO_GENERATED item must not have been dispatched")

    def test_unknown_order_item_id_returns_error(self):
        from database import ProductType
        product_id = self._make_product(ProductType.AUTO_GENERATED)
        order_id, _item_id = self._make_order_with_item(product_id)
        result = self.ds.dispatch(order_id, order_item_id=999_999)
        self.assertIn("not found", result.error)


if __name__ == "__main__":
    unittest.main()
